/* const PREPARATION_MINUTES_PER_LAYER = 2;
const NUMBER_OF_LAYERS = 20;

function stimatedTime (PREPARATION_MINUTES_PER_LAYER, NUMBER_OF_LAYERS) {
  return PREPARATION_MINUTES_PER_LAYER * NUMBER_OF_LAYERS;
}

const EXPECTED_MINUTES_IN_OVEN = stimatedTime;

console.log (EXPECTED_MINUTES_IN_OVEN);
 */
/* const PREPARATION_MINUTES_PER_LAYER = 2;
const NUMBER_OF_LAYERS = 20;

function estimatedTime(PREPARATION_MINUTES_PER_LAYER, NUMBER_OF_LAYERS) {
  return PREPARATION_MINUTES_PER_LAYER * NUMBER_OF_LAYERS;
}

const EXPECTED_MINUTES_IN_OVEN = estimatedTime(PREPARATION_MINUTES_PER_LAYER, NUMBER_OF_LAYERS);

console.log(EXPECTED_MINUTES_IN_OVEN); */

/* const PREPARATION_MINUTES_PER_LAYER = 2;
const NUMBER_OF_LAYERS = 20;
const EXPECTED_MINUTES_IN_OVEN = NUMBER_OF_LAYERS * PREPARATION_MINUTES_PER_LAYER;

console.log(EXPECTED_MINUTES_IN_OVEN
  );  */
